apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.natsstreaming
  metadata:
  - name: natsURL
    value: nats://nats:4222
  - name: natsStreamingClusterID
    value: stan
  - name: subscriptionType
    value: topic
